name: build

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: build project
        env:
          GOOS: "linux"
          GOARCH: "amd64"
        run: go build -o build/monstercat_linux_amd64 main.go
      - name: store binary
        uses: actions/upload-artifact@v2
        with:
          name: linux
          path: build/
  build_windows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: build project
        env:
          GOOS: "windows"
          GOARCH: "amd64"
        run: go build -o build/monstercat_windows_amd64.exe main.go
      - name: store binary
        uses: actions/upload-artifact@v2
        with:
          name: windows
          path: build/
  build_darwin_amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: build project
        env:
          GOOS: "darwin"
          GOARCH: "amd64"
        run: go build -o build/monstercat_darwin_amd64 main.go
      - name: store binary
        uses: actions/upload-artifact@v2
        with:
          name: darwin_amd64
          path: build/
  build_darwin_arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: build project
        env:
          GOOS: "darwin"
          GOARCH: "arm64"
        run: go build -o build/monstercat_darwin_arm64 main.go
      - name: store binary
        uses: actions/upload-artifact@v2
        with:
          name: darwin_arm64
          path: build/
  release:
    runs-on: ubuntu-latest
    needs: [build_linux, build_windows, build_darwin_amd64, build_darwin_arm64]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: download linux binary
        uses: actions/download-artifact@v2
        with:
          name: linux
          path: linux/
      - name: download windows binary
        uses: actions/download-artifact@v2
        with:
          name: windows
          path: windows/
      - name: download darwin amd64 binary
        uses: actions/download-artifact@v2
        with:
          name: darwin_amd64
          path: darwin_amd64/
      - name: download darwin arm64 binary
        uses: actions/download-artifact@v2
        with:
          name: darwin_arm64
          path: darwin_arm64/
      - name: upload artifacts to release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            linux/monstercat_linux_amd64
            windows/monstercat_windows_amd64.exe
            darwin_amd64/monstercat_darwin_amd64
            darwin_arm64/monstercat_darwin_arm64
