name: build

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main
  release:
    types:
      - published

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: build project
        env:
          GOOS: "linux"
          GOARCH: "amd64"
        run: go build -o build/monstercat main.go
      - name: store binary
        uses: actions/upload-artifact@v2
        with:
          name: linux
          path: build/monstercat
  build_windows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: build project
        env:
          GOOS: "windows"
          GOARCH: "amd64"
        run: go build -o build/monstercat.exe main.go
      - name: store binary
        uses: actions/upload-artifact@v2
        with:
          name: windows
          path: build/monstercat.exe
  release:
    runs-on: ubuntu-latest
    needs: [build_linux, build_windows]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: download linux binary
        uses: actions/download-artifact@v2
        with:
          name: linux
          path: linux/
      - name: download windows binary
        uses: actions/download-artifact@v2
        with:
          name: windows
          path: windows/
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            linux/monstercat
            windows/monstercat.exe
