name: build

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v4.2.2
      - name: setup golang
        uses: actions/setup-go@v5.2.0
        with:
          go-version-file: "go.mod"
      - name: add build file suffix
        if: ${{ matrix.goos == 'windows' }}
        run: echo "SUFFIX=.exe" >> $GITHUB_ENV
      - name: build project
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: go build -o build/monstercat_${{ matrix.goos }}_${{ matrix.goarch }}${{ env.SUFFIX }} main.go
      - name: store binary
        uses: actions/upload-artifact@v4.5.0
        with:
          name: ${{ matrix.goos }}_${{ matrix.goarch }}
          path: build/
  release:
    runs-on: ubuntu-latest
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: download all binaries
        uses: actions/download-artifact@v4.1.8
        with:
          path: build/
      - name: upload artifacts to release
        uses: softprops/action-gh-release@v2.2.1
        with:
          files: build/**/*
